"""create festival tables

Revision ID: 555c13b3f93a
Revises: 
Create Date: 2026-08-23 05:33:54.803821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '555c13b3f93a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('festivals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('timezone', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_festivals_slug'), 'festivals', ['slug'], unique=True)
    op.create_table('festival_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('festival_id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['festival_id'], ['festivals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('festival_id', 'slug', name='uq_festival_runs_festival_slug')
    )
    op.create_index(op.f('ix_festival_runs_festival_id'), 'festival_runs', ['festival_id'], unique=False)
    op.create_table('festival_days',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('festival_run_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['festival_run_id'], ['festival_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('festival_run_id', 'date', name='uq_festival_days_run_date')
    )
    op.create_index(op.f('ix_festival_days_festival_run_id'), 'festival_days', ['festival_run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_festival_days_festival_run_id'), table_name='festival_days')
    op.drop_table('festival_days')
    op.drop_index(op.f('ix_festival_runs_festival_id'), table_name='festival_runs')
    op.drop_table('festival_runs')
    op.drop_index(op.f('ix_festivals_slug'), table_name='festivals')
    op.drop_table('festivals')
    # ### end Alembic commands ###
