"""add artist mbid

Revision ID: 793d0dcc65c3
Revises: 7cee3ac4be86
Create Date: 2026-08-26 23:50:30.285376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '793d0dcc65c3'
down_revision: Union[str, Sequence[str], None] = '7cee3ac4be86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('mbid', sa.String(length=36), nullable=True))
    op.create_unique_constraint(op.f('artists_mbid_key'), 'artists', ['mbid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('artists_mbid_key'), 'artists', type_='unique')
    op.drop_column('artists', 'mbid')
    # ### end Alembic commands ###
