"""add artist domain schema

Revision ID: 7cee3ac4be86
Revises: 462e8e6a92ce
Create Date: 2026-08-23 22:04:26.578589

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7cee3ac4be86"
down_revision: Union[str, Sequence[str], None] = "462e8e6a92ce"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "artists",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("slug", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("spotify_artist_id", sa.String(length=100), nullable=True),
        sa.Column("image_url", sa.Text(), nullable=True),
        sa.Column("image_focal_y_percent", sa.SmallInteger(), nullable=True),
        sa.Column("image_credit_author", sa.String(length=200), nullable=True),
        sa.Column("image_source_url", sa.Text(), nullable=True),
        sa.Column("image_license_url", sa.Text(), nullable=True),
        sa.Column("image_taken_year", sa.SmallInteger(), nullable=True),
        sa.Column("image_sourced_at", sa.Date(), nullable=True),
        sa.Column("location_city", sa.String(length=100), nullable=True),
        sa.Column("location_state", sa.String(length=100), nullable=True),
        sa.Column("location_country", sa.String(length=100), nullable=True),
        sa.Column("about", sa.Text(), nullable=True),
        sa.Column("about_verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("youtube_url", sa.Text(), nullable=True),
        sa.Column("tiktok_url", sa.Text(), nullable=True),
        sa.Column(
            "socials_verified",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column("listen_first_note", sa.Text(), nullable=True),
        sa.Column(
            "publication_status",
            sa.String(length=20),
            server_default="draft",
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "publication_status IN ('draft', 'published')",
            name=op.f("ck_artists_publication_status"),
        ),
        sa.CheckConstraint(
            "about_verified_at IS NULL OR about IS NOT NULL",
            name=op.f("ck_artists_about_verification_requires_about"),
        ),
        sa.CheckConstraint(
            "image_focal_y_percent BETWEEN 0 AND 100",
            name=op.f("ck_artists_image_focal_y_percent_range"),
        ),
        sa.CheckConstraint(
            "image_url IS NOT NULL OR (image_focal_y_percent IS NULL AND image_credit_author IS NULL AND image_source_url IS NULL AND image_license_url IS NULL AND image_taken_year IS NULL AND image_sourced_at IS NULL)",
            name=op.f("ck_artists_image_metadata_requires_image"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("artists_pkey")),
        sa.UniqueConstraint(
            "spotify_artist_id", name=op.f("artists_spotify_artist_id_key")
        ),
    )
    op.create_index(op.f("ix_artists_slug"), "artists", ["slug"], unique=True)
    op.create_table(
        "genre_families",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("slug", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("display_order", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "display_order > 0", name=op.f("ck_genre_families_display_order_positive")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("genre_families_pkey")),
        sa.UniqueConstraint("display_order", name="uq_genre_families_display_order"),
        sa.UniqueConstraint("name", name=op.f("genre_families_name_key")),
    )
    op.create_index(
        op.f("ix_genre_families_slug"), "genre_families", ["slug"], unique=True
    )
    op.create_table(
        "tracks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("spotify_track_id", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("tracks_pkey")),
        sa.UniqueConstraint(
            "spotify_track_id", name=op.f("tracks_spotify_track_id_key")
        ),
    )
    op.create_table(
        "artist_track_selections",
        sa.Column("artist_id", sa.Integer(), nullable=False),
        sa.Column("track_id", sa.Integer(), nullable=False),
        sa.Column(
            "is_quick_picks",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column("listen_first_order", sa.SmallInteger(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "is_quick_picks OR listen_first_order IS NOT NULL",
            name=op.f("ck_artist_track_selections_has_role"),
        ),
        sa.CheckConstraint(
            "listen_first_order BETWEEN 1 AND 3",
            name=op.f("ck_artist_track_selections_listen_first_order_range"),
        ),
        sa.ForeignKeyConstraint(
            ["artist_id"],
            ["artists.id"],
            name=op.f("artist_track_selections_artist_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["track_id"],
            ["tracks.id"],
            name=op.f("artist_track_selections_track_id_fkey"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint(
            "artist_id", "track_id", name=op.f("artist_track_selections_pkey")
        ),
        sa.UniqueConstraint(
            "artist_id",
            "listen_first_order",
            name="uq_artist_track_selections_artist_listen_first_order",
        ),
    )
    op.create_index(
        op.f("ix_artist_track_selections_track_id"),
        "artist_track_selections",
        ["track_id"],
        unique=False,
    )
    op.create_index(
        "uq_artist_track_selections_one_quick_picks_per_artist",
        "artist_track_selections",
        ["artist_id"],
        unique=True,
        postgresql_where=sa.text("is_quick_picks"),
    )
    op.create_table(
        "artist_videos",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("artist_id", sa.Integer(), nullable=False),
        sa.Column("youtube_video_id", sa.String(length=100), nullable=False),
        sa.Column("label", sa.String(length=200), nullable=False),
        sa.Column(
            "is_featured", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("display_order", sa.Integer(), nullable=False),
        sa.Column("published_at", sa.Date(), nullable=True),
        sa.Column(
            "is_available", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.Column("last_checked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "display_order > 0", name=op.f("ck_artist_videos_display_order_positive")
        ),
        sa.ForeignKeyConstraint(
            ["artist_id"],
            ["artists.id"],
            name=op.f("artist_videos_artist_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("artist_videos_pkey")),
        sa.UniqueConstraint(
            "artist_id", "display_order", name="uq_artist_videos_artist_display_order"
        ),
        sa.UniqueConstraint(
            "artist_id",
            "youtube_video_id",
            name="uq_artist_videos_artist_youtube_video",
        ),
    )
    op.create_index(
        "uq_artist_videos_one_featured_per_artist",
        "artist_videos",
        ["artist_id"],
        unique=True,
        postgresql_where=sa.text("is_featured"),
    )
    op.create_table(
        "genres",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("family_id", sa.Integer(), nullable=False),
        sa.Column("slug", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["family_id"],
            ["genre_families.id"],
            name=op.f("genres_family_id_fkey"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("genres_pkey")),
        sa.UniqueConstraint("name", name=op.f("genres_name_key")),
    )
    op.create_index(op.f("ix_genres_family_id"), "genres", ["family_id"], unique=False)
    op.create_index(op.f("ix_genres_slug"), "genres", ["slug"], unique=True)
    op.create_table(
        "artist_genres",
        sa.Column("artist_id", sa.Integer(), nullable=False),
        sa.Column("genre_id", sa.Integer(), nullable=False),
        sa.Column("display_order", sa.Integer(), nullable=False),
        sa.Column(
            "is_primary", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "display_order BETWEEN 1 AND 3",
            name=op.f("ck_artist_genres_display_order_range"),
        ),
        sa.ForeignKeyConstraint(
            ["artist_id"],
            ["artists.id"],
            name=op.f("artist_genres_artist_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["genre_id"],
            ["genres.id"],
            name=op.f("artist_genres_genre_id_fkey"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint(
            "artist_id", "genre_id", name=op.f("artist_genres_pkey")
        ),
        sa.UniqueConstraint(
            "artist_id", "display_order", name="uq_artist_genres_artist_display_order"
        ),
    )
    op.create_index(
        op.f("ix_artist_genres_genre_id"), "artist_genres", ["genre_id"], unique=False
    )
    op.create_index(
        "uq_artist_genres_one_primary_per_artist",
        "artist_genres",
        ["artist_id"],
        unique=True,
        postgresql_where=sa.text("is_primary"),
    )
    op.create_table(
        "stages",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("festival_edition_id", sa.Integer(), nullable=False),
        sa.Column("slug", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("display_order", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "display_order > 0", name=op.f("ck_stages_display_order_positive")
        ),
        sa.ForeignKeyConstraint(
            ["festival_edition_id"],
            ["festival_editions.id"],
            name=op.f("stages_festival_edition_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("stages_pkey")),
        sa.UniqueConstraint(
            "festival_edition_id",
            "display_order",
            name="uq_stages_edition_display_order",
        ),
        sa.UniqueConstraint(
            "festival_edition_id", "name", name="uq_stages_edition_name"
        ),
        sa.UniqueConstraint(
            "festival_edition_id", "slug", name="uq_stages_edition_slug"
        ),
    )
    op.create_table(
        "lineup_entries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("festival_run_id", sa.Integer(), nullable=False),
        sa.Column("artist_id", sa.Integer(), nullable=False),
        sa.Column(
            "lineup_status",
            sa.String(length=20),
            server_default="draft",
            nullable=False,
        ),
        sa.Column("billing_tier", sa.String(length=20), nullable=True),
        sa.Column("announced_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("withdrawn_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "billing_tier IS NULL OR billing_tier IN ('headliner', 'sub_headliner', 'undercard')",
            name=op.f("ck_lineup_entries_billing_tier"),
        ),
        sa.CheckConstraint(
            "lineup_status <> 'draft' OR (announced_at IS NULL AND withdrawn_at IS NULL)",
            name=op.f("ck_lineup_entries_draft_has_no_event_timestamps"),
        ),
        sa.CheckConstraint(
            "lineup_status IN ('draft', 'announced', 'withdrawn')",
            name=op.f("ck_lineup_entries_status"),
        ),
        sa.CheckConstraint(
            "withdrawn_at IS NULL OR lineup_status = 'withdrawn'",
            name=op.f("ck_lineup_entries_withdrawn_at_matches_status"),
        ),
        sa.ForeignKeyConstraint(
            ["artist_id"],
            ["artists.id"],
            name=op.f("lineup_entries_artist_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["festival_run_id"],
            ["festival_runs.id"],
            name=op.f("lineup_entries_festival_run_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("lineup_entries_pkey")),
        sa.UniqueConstraint(
            "festival_run_id", "artist_id", name="uq_lineup_entries_run_artist"
        ),
    )
    op.create_index(
        op.f("ix_lineup_entries_artist_id"),
        "lineup_entries",
        ["artist_id"],
        unique=False,
    )
    op.create_table(
        "similar_artist_sets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("festival_run_id", sa.Integer(), nullable=False),
        sa.Column("source_artist_id", sa.Integer(), nullable=False),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["festival_run_id"],
            ["festival_runs.id"],
            name=op.f("similar_artist_sets_festival_run_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["source_artist_id"],
            ["artists.id"],
            name=op.f("similar_artist_sets_source_artist_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("similar_artist_sets_pkey")),
        sa.UniqueConstraint(
            "festival_run_id",
            "source_artist_id",
            name="uq_similar_artist_sets_run_source_artist",
        ),
    )
    op.create_index(
        op.f("ix_similar_artist_sets_source_artist_id"),
        "similar_artist_sets",
        ["source_artist_id"],
        unique=False,
    )
    op.create_table(
        "appearances",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("lineup_entry_id", sa.Integer(), nullable=False),
        sa.Column("festival_day_id", sa.Integer(), nullable=False),
        sa.Column("stage_id", sa.Integer(), nullable=False),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "appearance_status",
            sa.String(length=20),
            server_default="draft",
            nullable=False,
        ),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancellation_reason", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "appearance_status = 'cancelled' OR (cancelled_at IS NULL AND cancellation_reason IS NULL)",
            name=op.f("ck_appearances_cancellation_matches_status"),
        ),
        sa.CheckConstraint(
            "appearance_status IN ('draft', 'scheduled', 'cancelled')",
            name=op.f("ck_appearances_status"),
        ),
        sa.CheckConstraint(
            "ends_at > starts_at", name=op.f("ck_appearances_positive_duration")
        ),
        sa.ForeignKeyConstraint(
            ["festival_day_id"],
            ["festival_days.id"],
            name=op.f("appearances_festival_day_id_fkey"),
            ondelete="NO ACTION",
            deferrable=True,
            initially="DEFERRED",
        ),
        sa.ForeignKeyConstraint(
            ["lineup_entry_id"],
            ["lineup_entries.id"],
            name=op.f("appearances_lineup_entry_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["stage_id"],
            ["stages.id"],
            name=op.f("appearances_stage_id_fkey"),
            ondelete="NO ACTION",
            deferrable=True,
            initially="DEFERRED",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("appearances_pkey")),
    )
    op.create_index(
        op.f("ix_appearances_festival_day_id"),
        "appearances",
        ["festival_day_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_appearances_lineup_entry_id"),
        "appearances",
        ["lineup_entry_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_appearances_stage_id"), "appearances", ["stage_id"], unique=False
    )
    op.create_table(
        "similar_artists",
        sa.Column("similarity_set_id", sa.Integer(), nullable=False),
        sa.Column("target_artist_id", sa.Integer(), nullable=False),
        sa.Column("display_order", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "display_order BETWEEN 1 AND 4",
            name=op.f("ck_similar_artists_display_order_range"),
        ),
        sa.ForeignKeyConstraint(
            ["similarity_set_id"],
            ["similar_artist_sets.id"],
            name=op.f("similar_artists_similarity_set_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["target_artist_id"],
            ["artists.id"],
            name=op.f("similar_artists_target_artist_id_fkey"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint(
            "similarity_set_id", "target_artist_id", name=op.f("similar_artists_pkey")
        ),
        sa.UniqueConstraint(
            "similarity_set_id",
            "display_order",
            name="uq_similar_artists_set_display_order",
        ),
    )
    op.create_index(
        op.f("ix_similar_artists_target_artist_id"),
        "similar_artists",
        ["target_artist_id"],
        unique=False,
    )
    op.drop_index(op.f("ix_festival_days_festival_run_id"), table_name="festival_days")
    op.create_unique_constraint(
        "uq_festival_days_run_display_order",
        "festival_days",
        ["festival_run_id", "display_order"],
    )
    op.create_check_constraint(
        op.f("ck_festival_days_display_order_positive"),
        "festival_days",
        "display_order > 0",
    )
    op.drop_index(
        op.f("ix_festival_runs_festival_edition_id"), table_name="festival_runs"
    )
    op.create_unique_constraint(
        "uq_festival_runs_edition_display_order",
        "festival_runs",
        ["festival_edition_id", "display_order"],
    )
    op.create_check_constraint(
        op.f("ck_festival_runs_display_order_positive"),
        "festival_runs",
        "display_order > 0",
    )

    for table_name in (
        "artists",
        "genre_families",
        "genres",
        "artist_genres",
        "tracks",
        "artist_track_selections",
        "artist_videos",
        "similar_artist_sets",
        "similar_artists",
        "lineup_entries",
        "stages",
        "appearances",
    ):
        op.execute(
            f"""
            CREATE TRIGGER trg_{table_name}_updated_at
            BEFORE UPDATE ON {table_name}
            FOR EACH ROW
            EXECUTE FUNCTION set_updated_at_timestamp()
            """
        )

    op.execute(
        """
        CREATE FUNCTION invalidate_artist_editorial_verification()
        RETURNS TRIGGER AS $$
        BEGIN
            IF NEW.about IS DISTINCT FROM OLD.about THEN
                NEW.about_verified_at = NULL;
            END IF;

            IF NEW.youtube_url IS DISTINCT FROM OLD.youtube_url
               OR NEW.tiktok_url IS DISTINCT FROM OLD.tiktok_url THEN
                NEW.socials_verified = false;
            END IF;

            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql
        """
    )
    op.execute(
        """
        CREATE TRIGGER trg_artists_invalidate_editorial_verification
        BEFORE UPDATE OF about, youtube_url, tiktok_url ON artists
        FOR EACH ROW
        EXECUTE FUNCTION invalidate_artist_editorial_verification()
        """
    )

    op.execute(
        """
        CREATE FUNCTION invalidate_similar_artist_set_verification()
        RETURNS TRIGGER AS $$
        BEGIN
            IF TG_OP = 'DELETE' OR TG_OP = 'UPDATE' THEN
                UPDATE similar_artist_sets
                SET verified_at = NULL
                WHERE id = OLD.similarity_set_id;
            END IF;

            IF TG_OP = 'INSERT' THEN
                UPDATE similar_artist_sets
                SET verified_at = NULL
                WHERE id = NEW.similarity_set_id;
            ELSIF TG_OP = 'UPDATE'
                  AND NEW.similarity_set_id IS DISTINCT FROM OLD.similarity_set_id THEN
                UPDATE similar_artist_sets
                SET verified_at = NULL
                WHERE id = NEW.similarity_set_id;
            END IF;

            IF TG_OP = 'DELETE' THEN
                RETURN OLD;
            END IF;
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql
        """
    )
    op.execute(
        """
        CREATE TRIGGER trg_similar_artists_invalidate_verification
        AFTER INSERT OR UPDATE OR DELETE ON similar_artists
        FOR EACH ROW
        EXECUTE FUNCTION invalidate_similar_artist_set_verification()
        """
    )

    op.execute(
        """
        CREATE FUNCTION invalidate_similarity_for_departed_lineup_artist()
        RETURNS TRIGGER AS $$
        DECLARE
            should_invalidate boolean;
        BEGIN
            IF TG_OP = 'DELETE' THEN
                should_invalidate = OLD.lineup_status = 'announced';
            ELSE
                should_invalidate = OLD.lineup_status = 'announced'
                    AND (
                        NEW.lineup_status IS DISTINCT FROM 'announced'
                        OR NEW.festival_run_id IS DISTINCT FROM OLD.festival_run_id
                        OR NEW.artist_id IS DISTINCT FROM OLD.artist_id
                    );
            END IF;

            IF should_invalidate THEN
                UPDATE similar_artist_sets AS similarity_set
                SET verified_at = NULL
                WHERE similarity_set.verified_at IS NOT NULL
                  AND similarity_set.festival_run_id = OLD.festival_run_id
                  AND (
                      similarity_set.source_artist_id = OLD.artist_id
                      OR EXISTS (
                          SELECT 1
                          FROM similar_artists AS entry
                          WHERE entry.similarity_set_id = similarity_set.id
                            AND entry.target_artist_id = OLD.artist_id
                      )
                  );
            END IF;

            IF TG_OP = 'DELETE' THEN
                RETURN OLD;
            END IF;
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql
        """
    )
    op.execute(
        """
        CREATE TRIGGER trg_lineup_entries_invalidate_similarity_on_delete
        AFTER DELETE ON lineup_entries
        FOR EACH ROW
        EXECUTE FUNCTION invalidate_similarity_for_departed_lineup_artist()
        """
    )
    op.execute(
        """
        CREATE TRIGGER trg_lineup_entries_invalidate_similarity_on_update
        AFTER UPDATE OF lineup_status, festival_run_id, artist_id ON lineup_entries
        FOR EACH ROW
        EXECUTE FUNCTION invalidate_similarity_for_departed_lineup_artist()
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "DROP TRIGGER trg_lineup_entries_invalidate_similarity_on_update "
        "ON lineup_entries"
    )
    op.execute(
        "DROP TRIGGER trg_lineup_entries_invalidate_similarity_on_delete "
        "ON lineup_entries"
    )
    op.execute("DROP FUNCTION invalidate_similarity_for_departed_lineup_artist()")

    op.execute(
        "DROP TRIGGER trg_similar_artists_invalidate_verification ON similar_artists"
    )
    op.execute("DROP FUNCTION invalidate_similar_artist_set_verification()")

    op.execute("DROP TRIGGER trg_artists_invalidate_editorial_verification ON artists")
    op.execute("DROP FUNCTION invalidate_artist_editorial_verification()")

    for table_name in (
        "artists",
        "genre_families",
        "genres",
        "artist_genres",
        "tracks",
        "artist_track_selections",
        "artist_videos",
        "similar_artist_sets",
        "similar_artists",
        "lineup_entries",
        "stages",
        "appearances",
    ):
        op.execute(f"DROP TRIGGER trg_{table_name}_updated_at ON {table_name}")

    op.drop_constraint(
        op.f("ck_festival_runs_display_order_positive"), "festival_runs", type_="check"
    )
    op.drop_constraint(
        "uq_festival_runs_edition_display_order", "festival_runs", type_="unique"
    )
    op.create_index(
        op.f("ix_festival_runs_festival_edition_id"),
        "festival_runs",
        ["festival_edition_id"],
        unique=False,
    )
    op.drop_constraint(
        op.f("ck_festival_days_display_order_positive"), "festival_days", type_="check"
    )
    op.drop_constraint(
        "uq_festival_days_run_display_order", "festival_days", type_="unique"
    )
    op.create_index(
        op.f("ix_festival_days_festival_run_id"),
        "festival_days",
        ["festival_run_id"],
        unique=False,
    )
    op.drop_index(
        op.f("ix_similar_artists_target_artist_id"), table_name="similar_artists"
    )
    op.drop_table("similar_artists")
    op.drop_index(op.f("ix_appearances_stage_id"), table_name="appearances")
    op.drop_index(op.f("ix_appearances_lineup_entry_id"), table_name="appearances")
    op.drop_index(op.f("ix_appearances_festival_day_id"), table_name="appearances")
    op.drop_table("appearances")
    op.drop_index(
        op.f("ix_similar_artist_sets_source_artist_id"),
        table_name="similar_artist_sets",
    )
    op.drop_table("similar_artist_sets")
    op.drop_index(op.f("ix_lineup_entries_artist_id"), table_name="lineup_entries")
    op.drop_table("lineup_entries")
    op.drop_table("stages")
    op.drop_index(
        "uq_artist_genres_one_primary_per_artist",
        table_name="artist_genres",
        postgresql_where=sa.text("is_primary"),
    )
    op.drop_index(op.f("ix_artist_genres_genre_id"), table_name="artist_genres")
    op.drop_table("artist_genres")
    op.drop_index(op.f("ix_genres_slug"), table_name="genres")
    op.drop_index(op.f("ix_genres_family_id"), table_name="genres")
    op.drop_table("genres")
    op.drop_index(
        "uq_artist_videos_one_featured_per_artist",
        table_name="artist_videos",
        postgresql_where=sa.text("is_featured"),
    )
    op.drop_table("artist_videos")
    op.drop_index(
        "uq_artist_track_selections_one_quick_picks_per_artist",
        table_name="artist_track_selections",
        postgresql_where=sa.text("is_quick_picks"),
    )
    op.drop_index(
        op.f("ix_artist_track_selections_track_id"),
        table_name="artist_track_selections",
    )
    op.drop_table("artist_track_selections")
    op.drop_table("tracks")
    op.drop_index(op.f("ix_genre_families_slug"), table_name="genre_families")
    op.drop_table("genre_families")
    op.drop_index(op.f("ix_artists_slug"), table_name="artists")
    op.drop_table("artists")
    # ### end Alembic commands ###
